Simplified Language-Selection
DivineThreepwood/bcozy pull request #41
Opened 2017-09-10 12:14 UTC by Zukye

Languages are now provided in a list loaded from available property files instead of comparing strings when filling the language selection dropdown. 
Initially shown language is now correct.

2017-09-11 11:25 UTC, DivineThreepwood requested changes
Nice enhancement!
Only some minor code issues.

2017-09-11 11:25 UTC, DivineThreepwood commented on src/main/java/org/openbase/bco/bcozy/view/ObserverButton.java
> + * <p>
please remove this artifacts

2017-09-11 11:25 UTC, DivineThreepwood commented on src/main/java/org/openbase/bco/bcozy/util/Languages.java
> +            this.languages = Arrays.asList(english, fromLocale(Locale.GERMANY));
Why is the fallback language forced to german?
Can this be replaced by `Locale.getDefault(`) ?

2017-09-11 11:25 UTC, DivineThreepwood commented on src/main/java/org/openbase/bco/bcozy/view/ObserverText.java
> +        this.update(null, null);
null should not be used as default argument.
If possible introduce a additional methods without arguments.

2017-09-11 13:51 UTC, Zukye commented
all issues fixed

2017-09-12 11:46 UTC, DivineThreepwood approved these changes

2017-09-12 11:46 UTC, merged